swagger: '2.0'
info:
  version: "0.0.1"
  title: XSS Vulnerable
  description: |
    <h1>Test</h1>
host: "petstore.swagger.io"
basePath: "/v2"
paths:
  /pet/findByStatus:
    get:
      responses:
        200:
          description: Successful response
