swagger: '2.0'
info:
  version: "0.0.1"
  title: XSS Vulnerable
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><script><path id="</script><img onerror=alert(1) src>">
host: "petstore.swagger.io"
basePath: "/v2"
paths:
  /pet/findByStatus:
    get:
      responses:
        200:
          description: Successful response
