swagger: '2.0'
info:
  version: "0.0.1"
  title: XSS Vulnerable
  description: |
    <math><mtext><table><mglyph><style><!--</style><img title="--&gt;&lt;img src=1 onerror=alert(1)&gt;">
host: "petstore.swagger.io"
basePath: "/v2"
paths:
  /pet/findByStatus:
    get:
      responses:
        200:
          description: Successful response
